package com.example.elvo.domain.enums

enum class ErrorCodes {
    INCORRECT_CREDENTIALS,
    USER_NOT_FOUND,
    BLANK_CREDENTIALS,
    SHORT_PASSWORD,
    USER_ALREADY_EXISTS,
    SERVER_ERROR,
    SESSION_EXPIRED,
    INVALID_LOGIN,
    INVALID_PASSWORD,
    INVALID_CONFIRMING_PASSWORD,
    CHECK_CREDENTIALS,
    UNKNOWN_ERROR,
    REQUIRED_FIELD_EMPTY,
    NOTHING_CHANGED,
    RECIPIENT_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    INCORRECT_PHONE,
    INCORRECT_ADDRESS,
    INCORRECT_NAME,
    UNAUTHORIZED,
    USER_INFO_LOADING_ERROR,
    ORDER_NOT_FOUND,
    INCORRECT_LINK,
    INCORRECT_ORDER_DATA,
    IMPOSSIBLE_TO_PAY
}