package com.example.elvo.domain.enums

enum class ErrorCodes {
    INCORRECT_CREDENTIALS,
    USER_NOT_FOUND,
    BLANK_CREDENTIALS,
    SHORT_PASSWORD,
    USER_ALREADY_EXISTS,
    SERVER_ERROR,
    SESSION_EXPIRED,
    INVALID_LOGIN,
    INVALID_PASSWORD,
    INVALID_CONFIRMING_PASSWORD,
    CHECK_CREDENTIALS,
    UNKNOWN_ERROR
}